<?php

declare(strict_types=1);

/** Demo Roman Pali labels for UI chrome (not canonical CST). */
return [
    'home' => 'Mūla',
    'menu_examinations' => 'Parikkhā',
    'menu_about' => 'Nidāna',
    'menu_help' => 'Anuggaha',
    'menu_more' => 'Aparaṃ',
    'menu_content' => 'Potthaka',
    'menu_administration' => 'Parihāra',
    'login' => 'Pavisati',
    'register' => 'Lekhāpeti',
    'admin_panel' => 'Adhipati-maṇḍala',
    'dashboard' => 'Sārasaṅkhepa',
    'monastery' => 'Vihāra',
    'monastery_portal' => 'Vihāra-dvāra',
    'sangha_label' => 'Saṅgha',
    'pass_sangha_list' => 'Jina-saṅgha-nāmāvalī',
    'quick_links' => 'Sīgha-sambandhā',
    'exams' => 'Parikkhā',
    'scores' => 'Aṅka',
    'monasteries' => 'Vihārā',
    'sanghas' => 'Saṅghā',
    'users' => 'Upayogakārī',
    'recent_monasteries' => 'Navavihārā',
    'recent_exams' => 'Navaparikkhā',
    'recent_scores' => 'Navāṅkā',
    'dashboard_welcome_admin' => 'Adhipati-maṇḍale svāgataṃ. Vihāra-saṅgha-parikkhā-upayogakārī pariharantu.',
    'overview' => 'Sārasaṅkhepa',
    'view' => 'Passati',
    'save' => 'Rakkhati',
    'cancel' => 'Paṭikkhipati',
    'exit' => 'Nikkhamati',
    'theme_light' => 'Āloka',
    'theme_dark' => 'Andhakāra',
    'theme_system' => 'Yantra',
    'view_site' => 'Jaālakaṃ passati',
    'home_hero_title' => 'Vihāra-saṅghānaṃ pāli-dhamma-parikkhā',
    'home_highlight_1_title' => 'Vihāra-dvāra',
    'home_highlight_2_title' => 'Saṅgha-phala',
    'home_highlight_3_title' => 'Pākaṭa-tārikā',
    'home_upcoming_exams' => 'Āyātī parikkhā',
    'home_explore_title' => 'Jaālakaṃ anvesati',
    'monastery_portal_open_screen_hint' => 'Paṭalaṃ phusitvā aññaṃ āvaraṇaṃ vivarati',
    'new_sangha' => 'Nava-saṅgha',
    'total' => 'Samudāya',
    'pending' => 'Paṭighātī',
    'approved' => 'Anujñāta',
    'rejected' => 'Paṭikkhaṭa',
    'monastery_requests' => 'Saṅgha-saṇṭhāna',
    'chat' => 'Sallāpa',
    'results' => 'Phala',
    'pass_list' => 'Jina-nāmāvalī',
    'fail_list' => 'Parājita-nāmāvalī',
    'menu_exam_eligible_candidates' => 'Parikkhā-gabbha-yogī',
    'student_login' => 'Sissā pavisati',
    'monastery_login' => 'Vihāra-pavisana',
    'admin_login' => 'Adhipati-pavisana',
];
